# Generated by Django 6.0.7 on 2026-07-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_folder_note_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends Only'), ('private', 'Private')], default='private', max_length=10),
        ),
    ]
